import type { Metadata } from "next";
import localFont from "next/font/local";
import TopNavbar from "../components/TopNavbar/TopNavbar"; // Import TopNavbar
import SideNavbar from "../components/SideNavbar/SideNavbar"; // Import SideNavbar
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopNavbar /> 
        <SideNavbar /> 
        <div className="content"> {/* Wrapper for page-specific content */}
          {children} {/* This renders the content of each page */}
        </div>
      </body>
    </html>
  );
}
